PRM_DATA/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

from pages.views import home_view

urlpatterns = [
    path('', home_view, name='home'),
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('pages/', include('pages.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'
urlpatterns = [
    path('incremental_import/', views.incremental_import_view, name='incremental_import'),
    path('convert/', views.convert_view, name='convert'),
    path('import_data/', views.import_data_view, name='import_data'),
    path('show_survey/', views.show_survey_view, name='show_survey'),
]

data/models.py
from django.db import models


# Create your models here.
class Survey(models.Model):
    name = models.CharField(unique=True, max_length=256)

    class Meta:
        db_table = 'surveys'


class ItemType(models.Model):
    name = models.CharField(unique=True, max_length=256)
    has_options = models.BooleanField(default=False)
    has_statements = models.BooleanField(default=False)

    class Meta:
        db_table = 'item_types'


class AnswerType(models.Model):
    name = models.CharField(unique=True, max_length=256)

    class Meta:
        db_table = 'answer_types'


class Item(models.Model):
    # TODO: remove survey when routing is ready
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    item_type = models.ForeignKey(ItemType, on_delete=models.CASCADE)
    answer_type = models.ForeignKey(AnswerType, on_delete=models.CASCADE)
    # TODO: remove seq_nr when routing is ready
    seq_nr = models.IntegerField()
    item_text = models.TextField(max_length=4000)
    display_direction = models.CharField(max_length=10, null=True, blank=True)
    add_text_box_other = models.BooleanField(default=False)
    # TODO: remove page_nr when routing is ready
    page_nr = models.IntegerField()
    # TODO: remove next_page when routing is ready
    next_page = models.IntegerField()
    spss_variable = models.CharField(max_length=32)
    spss_variable_label = models.CharField(max_length=256)
    spss_missing_value = models.CharField(max_length=16)
    spss_format = models.CharField(max_length=16)

    class Meta:
        db_table = 'items'


class ItemOption(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    seq_nr = models.IntegerField()
    option_text = models.CharField(max_length=256)
    # TODO: remove next_page when routing is ready
    next_page = models.IntegerField()
    spss_value_label = models.CharField(max_length=256)
    score = models.IntegerField()

    class Meta:
        db_table = 'item_options'


class ItemStatement(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    seq_nr = models.IntegerField()
    statement_text = models.CharField(max_length=256)
    spss_variable = models.CharField(max_length=32)
    spss_variable_label = models.CharField(max_length=256)
    spss_missing_value = models.CharField(max_length=16)
    spss_format = models.CharField(max_length=16)

    class Meta:
        db_table = 'item_statements'

pages/templates/pages/complete_data.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% for opmerking in opmerkingen %}
            <p>{{ opmerking|safe }}</p>
        {% endfor %}
    </div>

    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
{% endblock %}

pages/templates/pages/convert.html
{% extends 'base.html' %}
{% block content %}
    <div>
        Vragenlijst: {{ lijst }}
        <br>
        <br>
        Soorten:
        <br>
        {% for soort in soorten %}
            {{ soort.id }} - {{ soort.naam }}<br>
        {% endfor %}
        <br>
        <br>
        Vragen:
        {% for vraag in vragen %}
            <p>{{ vraag.tekst }}</p>
        {% endfor %}
        <br>
        <br>
        Opmerkingen:
        {% for opmerking in opmerkingen %}
            <p>{{ opmerking|safe }}</p>
        {% endfor %}
    </div>

    {# The following lines should be last in this file #}
    <script>
        hideSpinner();
    </script>
{% endblock %}

pages/templates/pages/fill.html
{% extends 'base.html' %}
{% block content %}
    <div>
        Vragenlijst: {{ lijst }}
        <br>
        <br>
        Soorten:
        <br>
        {% for soort in soorten %}
            {{ soort.id }} - {{ soort.naam }}<br>
        {% endfor %}
        <br>
        <br>
        Vragen:
        {% for vraag in vragen %}
            <p>{{ vraag.tekst }}</p>
        {% endfor %}
        <br>
        <br>
        Opmerkingen:
        {% for opmerking in opmerkingen %}
            <p>{{ opmerking|safe }}</p>
        {% endfor %}
    </div>

    {# The following lines should be last in this file #}
    <script>
        hideSpinner();
    </script>
{% endblock %}

pages/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
{% endblock %}

pages/templates/pages/import_data.html
{% extends 'base.html' %}
{% block content %}

    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
{% endblock %}

pages/templates/pages/incremental_import.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% for opmerking in opmerkingen %}
            <p>{{ opmerking|safe }}</p>
        {% endfor %}
    </div>

    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
{% endblock %}

pages/templates/pages/show_items.html
{% extends 'base.html' %}
{% block content %}
    <h3>Survey {{ survey.name }} contains {{ items.count }} items </h3>
    ITEM: Seq nr / Item type / Item ID<br>
    SPSS: variable | variable_label | missing_value | format<br>
    VALUE_LABELS: not always necessary
    <hr>
    {% for item in items %}
        <div class="item-hdr">ITEM: {{ item.seq_nr }} / {{ item.item_type.name }}
            / {{ item.id }}<br>
            {% if not item.item_type.has_statements %}
                SPSS: {{ item.spss_variable }}
                | {{ item.spss_variable_label }} | {{ item.spss_missing_value }} |
                {{ item.spss_format }}<br>
            {% else %}
                {% for item_statement in item.itemstatement_set.all %}
                    SPSS: {{ item_statement.spss_variable }}
                    | {{ item_statement.spss_variable_label }} |
                    {{ item_statement.spss_missing_value }} |
                    {{ item_statement.spss_format }}
                    <br>
                {% endfor %}
            {% endif %}
            {% if item.item_type.has_options %}
                VALUE_LABELS:
                {% for item_option in item.itemoption_set.all %}
                    {{ item_option.spss_value_label }}
                    {% if forloop.counter < item.itemoption_set.count %} #
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="item-input">
            {{ item.item_text|safe }}<br>
            {% if item.item_type_id == 1 %}
                <textarea name="item_{{ item.id }}"></textarea>
            {% elif item.item_type_id == 2 %}
                {% for item_option in item.itemoption_set.all %}
                    <input type="radio"
                           id="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}"
                           name="item_{{ item.id }}"
                           value="{{ item_option.seq_nr }}">
                    <label for="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}">{{ item_option.option_text }}</label>
                    {% if item.display_direction == 'vertical' %}
                        <br>
                    {% endif %}
                {% endfor %}
                {% if item.add_text_box_other %}
                    <input type="radio"
                           id="n_{{ item.seq_nr }}_{{ item.itemoption_set.count|add:"1" }}"
                           name="item_{{ item.id }}"
                           value="{{ item.itemoption_set.count|add:"1" }}">
                    <label for="n_{{ item.seq_nr }}_{{ item.itemoption_set.count|add:"1" }}">Other</label>
                    <input type="text" name="item_{{ item.id }}_2">
                {% endif %}
            {% elif item.item_type_id == 3 %}
                {% for item_option in item.itemoption_set.all %}
                    <input type="checkbox"
                           id="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}"
                           name="item_{{ item.id }}"
                           value="{{ item_option.seq_nr }}">
                    <label for="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}">{{ item_option.option_text }}</label>
                    {% if item.display_direction == 'vertical' %}
                        <br>
                    {% endif %}
                {% endfor %}
            {% elif item.item_type_id == 4 %}
                {% if item.answer_type_id == 1 %}
                    <input type="text" name="item_{{ item.id }}">
                {% elif item.answer_type_id == 2 %}
                    <input type="number"
                           name="n_{{ item.survey_id }}_{{ item.seq_nr }}">
                {% elif item.answer_type_id == 3 %}
                    <input type="date" name="item_{{ item.id }}">
                {% endif %}
            {% elif item.item_type_id == 5 %}
                {# just a note:) #}
            {% elif item.item_type_id == 6 %}
                <table>
                    <tr>
                        <td></td>
                        {% for item_option in item.itemoption_set.all %}
                            <th>{{ item_option.option_text }}</th>
                        {% endfor %}
                    </tr>
                    {% for item_statement in item.itemstatement_set.all %}
                        <tr>
                            <td>{{ item_statement.statement_text }}</td>
                            {% for item_option in item.itemoption_set.all %}
                                <td><input type="radio"
                                           name="statement_{{ item_statement.id }}">
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% elif item.item_type_id == 7 %}
                <div style="color:red">Nog niet geimplementeerd!</div>
            {% endif %}
        </div>
        <hr>
    {% endfor %}
    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
    <style>
        .item-hdr {
            font-size: small;
        }
        .item-input {
            background-color: skyblue;
            padding: 6px;
        }
    </style>
{% endblock %}

pages/templates/pages/show_survey.html
{% extends 'base.html' %}
{% block content %}
    <h3>Survey {{ survey.name }} contains {{ items.count }} items </h3>
    ITEM: Seq nr / Item type / Item ID<br>
    SPSS: variable | variable_label | missing_value | format<br>
    VALUE_LABELS: not always necessary
    <hr>
    {% for item in items %}
        <div class="item-info">ITEM: {{ item.seq_nr }} / {{ item.item_type.name }}
            ({{ item.item_type_id }})
            / {{ item.id }}<br>
            {% if not item.item_type.has_statements %}
                SPSS: {{ item.spss_variable }}
                | {{ item.spss_variable_label }} | {{ item.spss_missing_value }} |
                {{ item.spss_format }}<br>
            {% else %}
                {% for item_statement in item.itemstatement_set.all %}
                    SPSS: {{ item_statement.spss_variable }}
                    | {{ item_statement.spss_variable_label }} |
                    {{ item_statement.spss_missing_value }} |
                    {{ item_statement.spss_format }}
                    <br>
                {% endfor %}
            {% endif %}
            {% if item.item_type.has_options %}
                VALUE_LABELS:
                {% for item_option in item.itemoption_set.all %}
                    {{ item_option.spss_value_label }}
                    {% if forloop.counter < item.itemoption_set.count %} #
                    {% endif %}
                {% endfor %}
                <br>
                SCORES:
                {% for item_option in item.itemoption_set.all %}
                    {{ item_option.score }}
                    {% if forloop.counter < item.itemoption_set.count %} #
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
        <div class="item-input">
            {{ item.item_text|safe }}<br>
            {% if item.item_type_id == 1 %}
                <textarea name="item_{{ item.id }}"></textarea>
            {% elif item.item_type_id == 2 %}
                {% for item_option in item.itemoption_set.all %}
                    <input type="radio"
                           id="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}"
                           name="item_{{ item.id }}"
                           value="{{ item_option.seq_nr }}">
                    <label for="n_{{ item.seq_nr }}_{{ item_option.seq_nr }}">{{ item_option.option_text }}</label>
                    {% if item.display_direction == 'vertical' %}
                        <br>
                    {% endif %}
                {% endfor %}
                {% if item.add_text_box_other %}
                    <input type="radio"
                           id="n_{{ item.seq_nr }}_{{ item.itemoption_set.count|add:"1" }}"
                           name="item_{{ item.id }}"
                           value="{{ item.itemoption_set.count|add:"1" }}">
                    <label for="n_{{ item.seq_nr }}_{{ item.itemoption_set.count|add:"1" }}">Other</label>
                    <input type="text" name="item_{{ item.id }}_2">
                {% endif %}
            {% elif item.item_type_id == 3 %}
                {% for item_statetement in item.itemstatement_set.all %}
                    <input type="checkbox"
                           id="n_{{ item.seq_nr }}_{{ item_statetement.seq_nr }}"
                           name="item_{{ item.id }}"
                           value="{{ item_statetement.seq_nr }}">
                    <label for="n_{{ item.seq_nr }}_{{ item_statetement.seq_nr }}">{{ item_statetement.statement_text }}</label>
                    {% if item.display_direction == 'vertical' %}
                        <br>
                    {% endif %}
                {% endfor %}
            {% elif item.item_type_id == 4 %}
                {% if item.answer_type_id == 1 %}
                    <input type="text" name="item_{{ item.id }}">
                {% elif item.answer_type_id == 2 %}
                    <input type="number"
                           name="n_{{ item.survey_id }}_{{ item.seq_nr }}">
                {% elif item.answer_type_id == 3 %}
                    <input type="date" name="item_{{ item.id }}">
                {% endif %}
            {% elif item.item_type_id == 5 %}
                {# just a note:) #}
            {% elif item.item_type_id == 6 %}
                <table>
                    <tr>
                        <td></td>
                        {% for item_option in item.itemoption_set.all %}
                            <th style="text-align: center">{{ item_option.option_text }}</th>
                        {% endfor %}
                    </tr>
                    {% for item_statement in item.itemstatement_set.all %}
                        <tr>
                            <td>{{ item_statement.statement_text }}</td>
                            {% for item_option in item.itemoption_set.all %}
                                <td style="text-align: center"><input type="radio"
                                           name="statement_{{ item_statement.id }}">
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            {% elif item.item_type_id == 7 %}
                <div style="color:red">Nog niet geimplementeerd!</div>
            {% endif %}
        </div>
        <hr>
    {% endfor %}
    {# The following lines should be last in this file #}
    <script>
        hideSpinner()
    </script>
{% endblock %}